### PR TITLE
Improves all remember's mailer

### PR DESCRIPTION
**Pull request by patrickemuller**
- Changes old `.text.erb` mailers to `.html.slim`
- Adds Google Maps for buyers and producers
- Fixes subjects
- Improves layout for all remember mailers

### CODE REVIEW

**Comment by ssjr** [comment]
Why change `.text` to `.html`? keep both

**Comment by patrickemuller** [comment]
Why keep both?

**Comment by ssjr** [comment]
> WHY USE PLAIN TEXT?
> Even when you’re sending out an HTML email, a plain text alternative is crucial. Multi-part MIME (Multipurpose Internet Mail Extensions) bundles together a simplified plain text version of your email along with the HTML version of your email. Unless you’re sending out a solely plain text email, multi-part MIME should be part of every email campaign. Some great reasons why sending in multi-part MIME is a necessity:
> - Spam filters like to see a plain text alternative. HTML-only emails are a red flag for spam filters. A lazy spammer wouldn’t take time to create a plain text alternative so make sure you do!
> - Some email clients and apps can’t handle HTML. While it’s not as common as it used to be, some email clients do not support or display HTML properly. In instances like this, the plain text email will render instead.
> - Some people simply prefer it. Plain and simple—some people prefer text emails. Since a variety of email clients give their users the option to only receive the plain text version of an email, it’s important to send in multi-part MIME format. Otherwise, if your subscribers have enabled this setting and you only send an HTML version, they may not receive your email at all.

https://litmus.com/blog/best-practices-for-plain-text-emails-a-look-at-why-theyre-important

**Comment by patrickemuller** [comment]
The problem is that we have informations that we can't show using just text :cry: 
Google Maps is the main reason here. But I agree that we can have both options anyway.

**Comment by ssjr** [comment]
iframe? just remove in text version. can be 2 different versions

**Pull request merged**
